# Gets Hand dirty with Numpy

## Numpy Array Creation

In [1]:
import numpy as np

In [20]:
# Method 1
display(np.array([1,2,3])) # 1D Numpy array creation with array

# Method 2
display(np.array([[1,2,3],[4,5,6]])) # 2D Numpy array creation

# Method 3
display(np.arange(1,10,1)) # Numpy array creation with a range

# Method 4
display(np.linspace(1,20,20,dtype=int)) # Numpy array with evenly spaced size 20 values from 1 to 10. Defining dtype for the type of numbers

#Method 5
display(np.zeros((5,5))) # Creating Numpy array of size 5 and 5 all zero value array.

#Method 6
display(np.ones((5,5))) # Creating Numpy all one value array of size 5 & 5

#Method 7
display(np.full((5,5),fill_value=10)) # Creating Numpy array with value as 10

#Method 8
display(np.random.random((2,2))) # Creating a random array

#Method 9
display(np.empty((3,3))) # Creating empty array

array([1, 2, 3])

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

array([[0.1506786 , 0.80545749],
       [0.75834002, 0.14337844]])

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

## Operations on Numpy Array

In [30]:
#Reshaping an Array
display(np.arange(1,11,1).reshape(2,5)) # Numpy reshape method to convert 1D array into 2D array

#Shallow copy of an array
sourceArray = np.arange(1,11,1)
copiedArray = np.copy(sourceArray)

#Deep copy an array
arr = np.array([[1,2,3],[4,5,6]])
arr1 = arr.copy() 

# Sorting an array
arr.sort()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Information about Numpy Array

In [40]:
arr = np.random.random((20,10))
display(arr.shape) # This tells about number of rows and cols

display(len(arr)) # This tells about number of rows

display(arr.ndim) # It tells about dimension.

display(arr.dtype) # It tells about the type of data it holds

(20, 10)

20

2

dtype('float64')

numpy.ndarray

## Numpy Array Manipulation

In [57]:
#Append of items 

arr1 = np.arange(1,5,1)
arr2 = np.arange(5,9,1)

display(np.append(arr1, arr2)) # Combining both the arrays into one single array

display(np.vstack((arr1, arr2))) # It works if the length of both array is same. It will create two rows and created an 2D array

display(np.hstack((arr1, arr2))) 

display(np.column_stack((arr1, arr2)))

display(np.concatenate((arr1, arr2))) # It append items

display(np.insert(arr1, 1, 5)) # inserting object at loc




array([1, 2, 3, 4, 5, 6, 7, 8])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

array([1, 2, 3, 4, 5, 6, 7, 8])

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 5, 2, 3, 4])

## Indexing in Numpy

In [70]:
#Slicing of 1D
arr1 = np.arange(1,5,1)
display(arr1[0]) # extracting specific item

display(arr1[0:2]) # extracting in a range

display(arr1[::-1]) # Extracting all items from array in reverse order

# Slicing of 2D
arr2D = np.random.random((10,10))
display(arr2D[0,0]) # 0 row and 0 column position

display(arr2D[0:5,0:5]) # top 5 rows and 5 cols

display(arr2D[:,:1]) # Selecting all rows and first columns

display(arr2D[::2,:1]) # Selecting all alternate rows and first columns

display(arr2D[arr2D > 0.7]) # Filtering records based on its value. Here we are selecting only details greater then 0.7




1

array([1, 2])

array([4, 3, 2, 1])

0.7341599968787564

array([[0.73416   , 0.12548042, 0.56028829, 0.58057037, 0.32663466],
       [0.55229293, 0.13739377, 0.94530655, 0.13419085, 0.92948475],
       [0.92946206, 0.01581445, 0.5756228 , 0.7280339 , 0.96558276],
       [0.90106163, 0.34090956, 0.74971027, 0.93311814, 0.26141708],
       [0.28093174, 0.02613143, 0.90948145, 0.57721205, 0.21830769]])

array([[0.73416   ],
       [0.55229293],
       [0.92946206],
       [0.90106163],
       [0.28093174],
       [0.17128581],
       [0.98934886],
       [0.00778718],
       [0.78284151],
       [0.98366359]])

array([[0.73416   ],
       [0.92946206],
       [0.28093174],
       [0.98934886],
       [0.78284151]])

array([0.73416   , 0.87197614, 0.94530655, 0.92948475, 0.71919004,
       0.96081328, 0.92946206, 0.7280339 , 0.96558276, 0.81714623,
       0.92026023, 0.90106163, 0.74971027, 0.93311814, 0.88994706,
       0.90948145, 0.99179113, 0.84624403, 0.70080132, 0.98934886,
       0.87408097, 0.88675269, 0.78284151, 0.94123331, 0.98366359,
       0.96781392])

## Slicing Array

In [84]:
arr1 = np.arange(1,25,1)

display(np.split(arr1, 2)) # It will split the array into equal parts of 2

display(np.split(arr1, (2,3))) # It will split the array into three parts [1,2], [3],[4...]

display(np.hsplit(arr1, 4)) # It will split the number of rows into equal parts. Tuple can also be used

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]

[array([1, 2]),
 array([3]),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24])]

[array([1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18]),
 array([19, 20, 21, 22, 23, 24])]

## Misc

In [91]:
# Flattern

arr = np.random.random((2,2))
display(arr.flatten()) # It will convert the array into 1D array

display(arr.T) # It will switch rows into cols

display(np.mean(arr))

display(np.median(arr))

display(np.std(arr)) # It calculates standard deviation

display(np.corrcoef(arr)) # It calculates co-efficient

array([0.95621231, 0.08994474, 0.98728628, 0.07855061])

array([[0.95621231, 0.98728628],
       [0.08994474, 0.07855061]])

0.5279984846878782

0.5230785267939388

0.4439050647582648

array([[1., 1.],
       [1., 1.]])